project:
  type: website

website:
  title: "nf-nest"
  sidebar:
    collapse-level: 1
    contents:
      - text: "Intro"
        file: intro.qmd
      - text: "Setup HPC account"
        file: setup.qmd
      - text: "Create an experiment repo"
        file: create-exp-repo.qmd
      - text: "Launch an experiment"
        file: launch.qmd
      - text: "Add Julia packages on HPC"
        file: pkg.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    linkcolor: black

editor: source

execute: 
  cache: false

knitr: true
