project:
  type: website
  render:
    - "*.qmd"

website:
  title: "nf-nest"
  sidebar:
    collapse-level: 1
    contents:
      - text: "Introduction"
        file: 01_intro.qmd
      - text: "Setup your HPC account"
        file: 02_setup.qmd
      - text: "Create an experiment repo"
        file: 03_create-exp-repo.qmd
      - text: "Launch an experiment"
        file: 04_launch.qmd
      - text: "Add Julia packages on HPC"
        file: 05_pkg.qmd
      - text: "Job cross products"
        file: 06_cross_product.qmd
      - text: "Combine outputs"
        file: 07_combine.qmd
      - text: "Containers"
        file: 08_containers.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    linkcolor: black
    mermaid:
      theme: neutral

editor: source

execute: 
  cache: true

knitr: true
